"""added fire_count to song model.

Revision ID: 3465d78af0f4
Revises: e5e032be0ba2
Create Date: 2024-03-27 01:31:07.171503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3465d78af0f4'
down_revision = 'e5e032be0ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fire_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('fire_count')

    # ### end Alembic commands ###
