"""added created_at and updated_at to song models.

Revision ID: 56639422d659
Revises: d2274afe66f6
Create Date: 2024-03-27 03:45:22.004369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56639422d659'
down_revision = 'd2274afe66f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
