"""made song and genre tables

Revision ID: 59b7402b1ad9
Revises: 546269a6fef2
Create Date: 2024-03-18 03:53:58.911678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b7402b1ad9'
down_revision = '546269a6fef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(), nullable=True),
    sa.Column('genre_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(), nullable=True),
    sa.Column('song_description', sa.String(), nullable=True),
    sa.Column('song_artwork', sa.String(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('upload_file', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], name=op.f('fk_songs_artist_id_users')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_songs_genre_id_genres')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('genres')
    # ### end Alembic commands ###
