"""accidentally added fire_count to comments now adding it to song.

Revision ID: d2274afe66f6
Revises: 3465d78af0f4
Create Date: 2024-03-27 01:36:07.847309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2274afe66f6'
down_revision = '3465d78af0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fire_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('fire_count')

    # ### end Alembic commands ###
